blog/urls.py
from django.urls import path
from .views import render_posts,post_detail

app_name= 'blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>',post_detail, name='post_detail')
    
]

django_portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
''' Parte importante para que funcione la carpeta 
midea '''
from django.conf import settings
from django.conf.urls.static import static
#impotamos views para poder ver nuestra nuestra vista principal
from portafolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    #Creamos la ruta principal del proyecto que se encuentra en la carpeta de portafolio
    path('',views.home, name='home'),
    path('blog/', include('blog.urls')),
]
''' Parte importante para que funcione la carpeta 
midea '''
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    desciption = models.TextField()
    image = models.ImageField(upload_to = 'blog/images')
    #deata manera le descimos al programa que si no ponemos una fecha en automatico ponga la fecha actual 
    date = models.DateField(datetime.date.today) 

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField

# Create your models here.

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portafolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.
def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts':posts})

def post_detail(request, post_id):
    post=get_object_or_404(Post,pk=post_id)
    return render(request,'post_detail.html', {"post":post})

portafolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.

'''Creamos la funcion para acceder a nuestra carpeta template'''
def home(request):
    projects=Project.objects.all()
    return render(request, 'home.html',{'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

    <div class="text-center">
        <h2>{{post.title}}</h2>
        <h3 class="my-2 h5 text-muted">{{post.date|date:'F jS Y'}}</h3>
        <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
    
        <!--|truncatechars:100 pasamos la cantidad de caracteres a mostrar   -->
        <!--|safe es para intrerpretar codigo html desde admin o de la cracion del proyecto-->
        <div class="my-4">
        <p>{{post.desciption}}</p>
        </div>
    </div>

    {% endblock %}

blog/templates/posts.html
{% extends 'layout.html'%}

{%block content%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    <h1>Hola esto es posts</h1>

    {% for post in posts %}

    <div class="p-3">
        <div class="card card-body bg-black">
            <div class="row">
                <div class="col-3">
                    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid"/>
                </div>
                <div class="col-9">
                    <h2>{{post.title}}</h2>
                    <h3>{{post.date}}</h3>
                    
                    <!--|truncatechars:100 pasamos la cantidad de caracteres a mostrar   -->
                    <!--|safe es para intrerpretar codigo html desde admin o de la cracion del proyecto-->
                    <p>{{post.desciption|truncatechars:100}}</p>
                    <!--DESTA MANERA PODEMOS FORMATEAR LA FECHA COMO MEJOR NOS PARESCA EN LA DOCUMNTACION DE 
                    DJANGO FILTROS DATETIME-->
                    <p>{{post.date|date:'M d Y'}}</p>
                    
                    <!--De esta manera creamos una ruta a nuestra ruta para nuestro proyecto-->
                    <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
                </div>
            </div>
        </div>

    </div>

    {% endfor %}

    {% endblock %}
</body>
</html>

portafolio/templates/home.html
{% extends 'layout.html'%}

{%block content%}

{% load static %}
<!-- Falto una parte al final dos 2 el 16/01/24-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>home</title>
    
</head>
<body>
    <!--la clase row es para poner el texto a la de la imagen-->
    <header class="row">
        <div class="col-md-4" style="margin-top: 20px;">
            <img src="{% static 'portfolio/Alonso.jpg' %}" alt="" width="400" height="400">
        </div>
        <div class="col-md-8 my-auto" style="margin-top: 20px;">
            <!-- Añade un margen superior de 20 píxeles (puedes ajustar este valor según tu preferencia) -->
            <h1>Mi nombre es <strong> Alonso Figueroa</strong></h1>
            <h3>Soy un principiante FullStack Developer Python</h3>
            
            <p style="text-align: justify;">Como principiante en el desarrollo FullStack, este proyecto me ha brindado una oportunidad 
                invaluable para explorar  y aplicar mis habilidades en el desarrollo web. A lo largo del
                proceso, he aprendido y experimentado con una variedad de tecnologías y herramientas 
                esenciales para construir aplicaciones web completas y funcionales. 
                <br><br>
                En la parte del frontend, he trabajado con HTML, CSS y JavaScript para crear una interfaz 
                de usuario atractiva y responsive. Además, he utilizado frameworks populares como Bootstrap
                para facilitar el diseño y mejorar la experiencia del usuario. La manipulación del DOM y 
                la interactividad del lado del cliente han sido áreas clave de enfoque.
                <br><br>
                En el backend, he empleado un framework como Django, aprovechando su potente capacidad 
                para gestionar la lógica de la aplicación y la interacción con la base de datos. 
                He diseñado modelos de datos, implementado vistas y manejado las rutas de URL para 
                construir una arquitectura robusta.
                <br><br>
                El uso de bases de datos, en particular, ha sido esencial para almacenar y recuperar 
                datos de manera eficiente. Además, he explorado conceptos como migraciones y consultas 
                para gestionar la evolución de la base de datos.
                <br><br>
                El control de versiones con Git ha sido fundamental para el desarrollo colaborativo y el 
                seguimiento de los cambios en el código. Asimismo, he desplegado la aplicación en entornos
                de desarrollo y producción, utilizando servicios como Heroku para ponerla en línea.
                <br><br>
                Este proyecto me ha desafiado a superar obstáculos, buscar soluciones y mejorar constantemente
                mis habilidades. A medida que avanzo como FullStack Developer, este proyecto representa 
                un hito significativo en mi viaje de aprendizaje y siento una base sólida para continuar 
                explorando nuevas tecnologías y abordando proyectos más complejos en el futuro.</p>
        </div>
</header>
<div class=" row my-4 text-center">
<!--desta manera podemos mostras nuestro contenido de nuestros preyectos-->
<h3>My Projects</h3>
<p style="text-align: justify;">Mis proyectos representan valiosas oportunidades de aprendizaje, 
    donde he adquirido conocimientos significativos y estoy ansioso por seguir mejorando cada día. 
    Cada proyecto ha sido una experiencia enriquecedora, permitiéndome expandir mis habilidades y
    enfrentar nuevos desafíos. Estoy motivado y comprometido a continuar mi desarrollo día a día,
    aprovechando cada proyecto como una plataforma para crecer y perfeccionar mis habilidades en 
    el fascinante mundo del desarrollo.</p>

{%for project in projects%}
<div class="col-md-4 p-4" >
    <div class="card bg-black card-project">
        <img src="{{ project.image.url }}" alt="{{ project.title }}" class="card-img-top"/>
        
        <div class="card-body">
            <h2 class="text-white">{{project.title}}</h2>
            <p class="text-white">{{project.description}}</p>
            <img src="{{projrct.image.url}}" alt=""/>
        </div>
        
        <!-- img-fluid con esto acomodamos nuestros proyectos-->
            
        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounder-0 btn-sm"> {{project.url}} </a>
        {%endif%}

        </div>
    </div>
</div>

{%endfor%}

{%endblock%}

</div>
</body>
</html>

portafolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<!--a qui cambiamos el color de texto de nuestra vista
-->
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <div class="container p4">
    {% block content %}

    {% endblock %}
    </div>
    
</body>
</html>

portafolio/templates/partials/navbar.html
<!--con esta linea importamos la carpeta static para poder ver lo que tengo la carpeta-->
<!--target="_blank este comando es para abrir un enlase de un archivo en otra pestaña-->
{% load static%}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
    <a class="navbar-brand fw-bold fst-ital " href="/">Jose Alonso Figueroa Martìnez</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav ms-auto">
                <li>
                    <a class="nav-link" href="/blog">Blog</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'portfolio/Entrvista_2.pdf'%}"target="_blank">Download CB</a>
                </li>
            </ul>   
        </div>
    </div>
</nav>